#include "token.h"

const char *token_type_name(TokenType type) {
    switch (type) {
        case TOKEN_EOF:
            return "TOKEN_EOF";
        case TOKEN_CLASS:
            return "TOKEN_CLASS";
        case TOKEN_TYPE_IDENTIFIER:
            return "TOKEN_TYPE_IDENTIFIER";
        case TOKEN_OBJECT_IDENTIFIER:
            return "TOKEN_OBJECT_IDENTIFIER";
        case TOKEN_IF:
            return "TOKEN_IF";
        case TOKEN_ELSE:
            return "TOKEN_ELSE";
        case TOKEN_FI:
            return "TOKEN_FI";
        case TOKEN_IN:
            return "TOKEN_IN";
        case TOKEN_INHERITS:
            return "TOKEN_INHERITS";
        case TOKEN_ISVOID:
            return "TOKEN_ISVOID";
        case TOKEN_LET:
            return "TOKEN_LET";
        case TOKEN_LOOP:
            return "TOKEN_LOOP";
        case TOKEN_POOL:
            return "TOKEN_POOL";
        case TOKEN_THEN:
            return "TOKEN_THEN";
        case TOKEN_WHILE:
            return "TOKEN_WHILE";
        case TOKEN_CASE:
            return "TOKEN_CASE";
        case TOKEN_ESAC:
            return "TOKEN_ESAC";
        case TOKEN_NEW:
            return "TOKEN_NEW";
        case TOKEN_OF:
            return "TOKEN_OF";
        case TOKEN_NOT:
            return "TOKEN_NOT";
        case TOKEN_BOOL_CONST:
            return "TOKEN_BOOL_CONST";
        case INT_CONST:
            return "INT_CONST";
        case STR_CONST:
            return "STR_CONST";
        case TOKEN_LBRACE:
            return "TOKEN_LBRACE";
        case TOKEN_RBRACE:
            return "TOKEN_RBRACE";
        case TOKEN_LBRACKET:
            return "TOKEN_LBRACKET";
        case TOKEN_RBRACKET:
            return "TOKEN_RBRACKET";  
        case TOKEN_LPAREN:
            return "TOKEN_LPAREN";
        case TOKEN_RPAREN:
            return "TOKEN_RPAREN";  
        case TOKEN_COMMA:
            return "TOKEN_COMMA";
        case TOKEN_COLON:
            return "TOKEN_COLON";
        case TOKEN_DOT:
            return "TOKEN_DOT";
        case TOKEN_AT:
            return "TOKEN_AT";
        case TOKEN_TILDE:
            return "TOKEN_TILDE";
        case TOKEN_SEMICOLON:
            return "TOKEN_SEMICOLON";
        case TOKEN_PLUS:
            return "TOKEN_PLUS";
        case TOKEN_MINUS:
            return "TOKEN_MINUS";
        case TOKEN_STAR:
            return "TOKEN_STAR";
        case TOKEN_SLASH:
            return "TOKEN_SLASH";
        case TOKEN_LE:
            return "TOKEN_LE";
        case TOKEN_GE:
            return "TOKEN_GE";
        case TOKEN_ASSIGN:
            return "TOKEN_ASSIGN";
        case TOKEN_LT:
            return "TOKEN_LT";
        case TOKEN_GT:
            return "TOKEN_GT";
        case TOKEN_EQUAL:
            return "TOKEN_EQUAL";
        case TOKEN_DARROW:
            return "TOKEN_DARROW";
        case TOKEN_ERROR:
            return "TOKEN_ERROR";
        default:
            return "TOKEN_UNKNOWN";
    }
}